const characterdata = [
    {
        id: 1,
        nameChar: "Sakura Bukushin O",
        imageChar: "/game-website-practice/uma musume web try-to-do/sakurabakushino_top.webp",
        boxcolor1: "#ff80b3",
        boxcolor2: "#F4D2D7",
    },
    {
        id: 2,
        nameChar: "Satono Daimond",
        imageChar: "/game-website-practice/uma musume web try-to-do/satonodiamond_top.webp",
        boxcolor1: "greenyellow",
        boxcolor2: "yellow",
    },
    {
        id: 1,
        nameChar: "Sakura Bukushin O",
        imageChar: "/game-website-practice/uma musume web try-to-do/sakurabakushino_top.webp",
        boxcolor1: "#ff80b3",
        boxcolor2: "#F4D2D7",
    },
    {
        id: 2,
        nameChar: "Satono Daimond",
        imageChar: "/game-website-practice/uma musume web try-to-do/satonodiamond_top.webp",
        boxcolor1: "greenyellow",
        boxcolor2: "yellow",
    },
    {
        id: 1,
        nameChar: "Sakura Bukushin O",
        imageChar: "/game-website-practice/uma musume web try-to-do/sakurabakushino_top.webp",
        boxcolor1: "#ff80b3",
        boxcolor2: "#F4D2D7",
    },
    {
        id: 2,
        nameChar: "Satono Daimond",
        imageChar: "/game-website-practice/uma musume web try-to-do/satonodiamond_top.webp",
        boxcolor1: "greenyellow",
        boxcolor2: "yellow",
    },
    {
        id: 1,
        nameChar: "Sakura Bukushin O",
        imageChar: "/game-website-practice/uma musume web try-to-do/sakurabakushino_top.webp",
        boxcolor1: "#ff80b3",
        boxcolor2: "#F4D2D7",
    },
    {
        id: 2,
        nameChar: "Satono Daimond",
        imageChar: "/game-website-practice/uma musume web try-to-do/satonodiamond_top.webp",
        boxcolor1: "greenyellow",
        boxcolor2: "yellow",
    },
    {
        id: 1,
        nameChar: "Sakura Bukushin O",
        imageChar: "/game-website-practice/uma musume web try-to-do/sakurabakushino_top.webp",
        boxcolor1: "#ff80b3",
        boxcolor2: "#F4D2D7",
    },
    {
        id: 2,
        nameChar: "Satono Daimond",
        imageChar: "/game-website-practice/uma musume web try-to-do/satonodiamond_top.webp",
        boxcolor1: "greenyellow",
        boxcolor2: "yellow",
    },
    {
        id: 1,
        nameChar: "Sakura Bukushin O",
        imageChar: "/game-website-practice/uma musume web try-to-do/sakurabakushino_top.webp",
        boxcolor1: "#ff80b3",
        boxcolor2: "#F4D2D7",
    },
    {
        id: 2,
        nameChar: "Satono Daimond",
        imageChar: "/game-website-practice/uma musume web try-to-do/satonodiamond_top.webp",
        boxcolor1: "greenyellow",
        boxcolor2: "yellow",
    },
    {
        id: 1,
        nameChar: "Sakura Bukushin O",
        imageChar: "/game-website-practice/uma musume web try-to-do/sakurabakushino_top.webp",
        boxcolor1: "#ff80b3",
        boxcolor2: "#F4D2D7",
    },
    {
        id: 2,
        nameChar: "Satono Daimond",
        imageChar: "/game-website-practice/uma musume web try-to-do/satonodiamond_top.webp",
        boxcolor1: "greenyellow",
        boxcolor2: "yellow",
    },
    {
        id: 1,
        nameChar: "Sakura Bukushin O",
        imageChar: "/game-website-practice/uma musume web try-to-do/sakurabakushino_top.webp",
        boxcolor1: "#ff80b3",
        boxcolor2: "#F4D2D7",
    },
    {
        id: 2,
        nameChar: "Satono Daimond",
        imageChar: "/game-website-practice/uma musume web try-to-do/satonodiamond_top.webp",
        boxcolor1: "greenyellow",
        boxcolor2: "yellow",
    },
]