const goodsdata = [
    {
        id: 1,
        category: "書籍",
        description: "ウマ娘 プリティーダービー アートワークス Vol.02",
        image: "/game-website-practice/uma musume web try-to-do/ウマ娘AW_Vol.02書影.webp",
    },
    {
        id: 2,
        category: "CD",
        description: "『ウマ娘 プリティーダービー』WINNING LIVE 24",
        image: "/game-website-practice/uma musume web try-to-do/YELL_NEWGATE_Blu-ray_top.webp",
    },
    {
        id: 3,
        category: "Blu-ray DVD",
        description: "ウマ娘 プリティーダービー 5th EVENT ARENA TOUR GO BEYOND -YELL- & -NEW GATE- Blu-ray",
        image: "/game-website-practice/uma musume web try-to-do/WL24_jacket.webp",
    },
    {
        id: 4,
        category: "Blu-ray DVD",
        description: "ウマ娘 プリティーダービー 5th EVENT ARENA TOUR GO BEYOND -YELL- & -NEW GATE- Blu-ray",
        image: "/game-website-practice/uma musume web try-to-do/WL24_jacket.webp",
    },
    {
        id: 1,
        category: "書籍",
        description: "ウマ娘 プリティーダービー アートワークス Vol.02",
        image: "/game-website-practice/uma musume web try-to-do/ウマ娘AW_Vol.02書影.webp",
    },
    {
        id: 2,
        category: "CD",
        description: "『ウマ娘 プリティーダービー』WINNING LIVE 24",
        image: "/game-website-practice/uma musume web try-to-do/YELL_NEWGATE_Blu-ray_top.webp",
    },
    {
        id: 3,
        category: "Blu-ray DVD",
        description: "ウマ娘 プリティーダービー 5th EVENT ARENA TOUR GO BEYOND -YELL- & -NEW GATE- Blu-ray",
        image: "/game-website-practice/uma musume web try-to-do/WL24_jacket.webp",
    },
    {
        id: 4,
        category: "Blu-ray DVD",
        description: "ウマ娘 プリティーダービー 5th EVENT ARENA TOUR GO BEYOND -YELL- & -NEW GATE- Blu-ray",
        image: "/game-website-practice/uma musume web try-to-do/WL24_jacket.webp",
    },
    {
        id: 1,
        category: "書籍",
        description: "ウマ娘 プリティーダービー アートワークス Vol.02",
        image: "/game-website-practice/uma musume web try-to-do/ウマ娘AW_Vol.02書影.webp",
    },
    {
        id: 2,
        category: "CD",
        description: "『ウマ娘 プリティーダービー』WINNING LIVE 24",
        image: "/game-website-practice/uma musume web try-to-do/YELL_NEWGATE_Blu-ray_top.webp",
    },
    {
        id: 3,
        category: "Blu-ray DVD",
        description: "ウマ娘 プリティーダービー 5th EVENT ARENA TOUR GO BEYOND -YELL- & -NEW GATE- Blu-ray",
        image: "/game-website-practice/uma musume web try-to-do/WL24_jacket.webp",
    },
    {
        id: 4,
        category: "Blu-ray DVD",
        description: "ウマ娘 プリティーダービー 5th EVENT ARENA TOUR GO BEYOND -YELL- & -NEW GATE- Blu-ray",
        image: "/game-website-practice/uma musume web try-to-do/WL24_jacket.webp",
    },
    {
        id: 1,
        category: "書籍",
        description: "ウマ娘 プリティーダービー アートワークス Vol.02",
        image: "/game-website-practice/uma musume web try-to-do/ウマ娘AW_Vol.02書影.webp",
    },
    {
        id: 2,
        category: "CD",
        description: "『ウマ娘 プリティーダービー』WINNING LIVE 24",
        image: "/game-website-practice/uma musume web try-to-do/YELL_NEWGATE_Blu-ray_top.webp",
    },
    {
        id: 3,
        category: "Blu-ray DVD",
        description: "ウマ娘 プリティーダービー 5th EVENT ARENA TOUR GO BEYOND -YELL- & -NEW GATE- Blu-ray",
        image: "/game-website-practice/uma musume web try-to-do/WL24_jacket.webp",
    },
    {
        id: 4,
        category: "Blu-ray DVD",
        description: "ウマ娘 プリティーダービー 5th EVENT ARENA TOUR GO BEYOND -YELL- & -NEW GATE- Blu-ray",
        image: "/game-website-practice/uma musume web try-to-do/WL24_jacket.webp",
    },
    {
        id: 1,
        category: "書籍",
        description: "ウマ娘 プリティーダービー アートワークス Vol.02",
        image: "/game-website-practice/uma musume web try-to-do/ウマ娘AW_Vol.02書影.webp",
    },
    {
        id: 2,
        category: "CD",
        description: "『ウマ娘 プリティーダービー』WINNING LIVE 24",
        image: "/game-website-practice/uma musume web try-to-do/YELL_NEWGATE_Blu-ray_top.webp",
    },
    {
        id: 3,
        category: "Blu-ray DVD",
        description: "ウマ娘 プリティーダービー 5th EVENT ARENA TOUR GO BEYOND -YELL- & -NEW GATE- Blu-ray",
        image: "/game-website-practice/uma musume web try-to-do/WL24_jacket.webp",
    },
    {
        id: 4,
        category: "Blu-ray DVD",
        description: "ウマ娘 プリティーダービー 5th EVENT ARENA TOUR GO BEYOND -YELL- & -NEW GATE- Blu-ray",
        image: "/game-website-practice/uma musume web try-to-do/WL24_jacket.webp",
    },
]